# Generated by Django 6.0.2 on 2026-02-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_employee_date_and_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
