# Generated by Django 6.0.2 on 2026-02-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_date_of_birth_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('техник', 'Техник'), ('инженер', 'Инженер'), ('разработчик', 'Разработчик')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='institute',
            field=models.CharField(blank=True, choices=[('НИУ ВШЭ', 'НИУ ВШЭ'), ('МФТИ', 'МФТИ'), ('Дауманка', 'Дауманка')], max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('C/C++', 'C/C++'), ('Rust', 'Rust'), ('Go', 'Go')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='tech_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='tech_rank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
